name: Build and Test
# This workflow builds and tests the application on push and pull request events.
# It runs on the main, stage, and dev branches.
# The workflow is triggered on push and pull request events.
# It runs on the main, stage, and dev branches.
# The workflow includes steps to checkout the repository, setup Node.js, install dependencies, and build the application.

on:
  push:
    branches: ["main", "stage", "dev"]
  pull_request:
    branches: ["main", "stage"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      # - name: Run tests
      #   run: npm test

      - name: Build application
        run: npm run build
