name: Bump Version

on:
  pull_request:
    types:
      - closed
    branches: ["main", "stage"]

jobs:
  bump_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessário para commitar e criar tag

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current version from package.json
        id: get_current_version
        run: |
          current_version=$(jq -r '.version' package.json)
          echo "CURRENT_VERSION=$current_version" >> $GITHUB_ENV

      - name: Verify type of bump
        id: check_label
        run: |
          bump="patch"
          if [[ $(echo "${{ toJson(github.event.pull_request.labels) }}" | grep "major") ]]; then
            bump="major"
          elif [[ $(echo "${{ toJson(github.event.pull_request.labels) }}" | grep "minor") ]]; then
            bump="minor"
          elif [[ $(echo "${{ toJson(github.event.pull_request.labels) }}" | grep "pre-release") ]]; then
            bump="pre"
          fi
          echo "BUMP_TYPE=$bump" >> $GITHUB_ENV

      - name: Increment Version
        id: bump_version
        run: |
          NEW_VERSION=$(node -e "
            const semver = require('semver');
            const currentVersion = '${{ env.CURRENT_VERSION }}';
            let bumpType = '${{ env.BUMP_TYPE }}';
            if (bumpType === 'pre') {
              bumpType = 'prerelease';
            }
            const newVersion = semver.inc(currentVersion, bumpType);
            console.log(newVersion);
          ")
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update package.json with new version
        run: |
          sed -i "s/\"version\": \"${{ env.CURRENT_VERSION }}\"/\"version\": \"${{ env.NEW_VERSION }}\"/" package.json
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add package.json
          git commit -m "Bump version to ${{ env.NEW_VERSION }}"
          git push origin ${{ github.head_ref }} # Empurra para a branch do PR mergeado

      - name: Create Git Tag
        id: create_tag
        run: |
          git tag -a "v${{ env.NEW_VERSION }}" -m "Version ${{ env.NEW_VERSION }}"
          git push origin --tags
