name: Update ArgoCD Manifest Tags

on:
  workflow_run:
    workflows: ["Bump Version and Dockerize"]
    types:
      - completed

jobs:
  update_argocd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Read version from artifact
        id: get_version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Checkout ArgoCD Manifest Repository (main branch)
        uses: actions/checkout@v4
        with:
          repository: gilsonrusso/argocd-trainning
          token: ${{ secrets.GH_TOKEN_VERSION_REPO }}
          path: argocd-trainning
          ref: main

      - name: Install yq
        run: sudo apt-get update && sudo apt-get install -y yq

      - name: Update values.prod.yaml (on merge to main)
        if: github.event.pull_request.base.ref == 'main'
        run: |
          cd argocd-trainning
          IMAGE_TAG="v${VERSION}"
          yq -y ".app.image.tag = \"$IMAGE_TAG\"" values.prod.yaml -i
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add values.prod.yaml
          git commit -m "Update production image tag to v${VERSION}"
          git push origin main

      - name: Update values.stage.yaml (on merge to stage)
        if: github.event.pull_request.base.ref == 'stage'
        run: |
          cd argocd-trainning
          IMAGE_TAG="v${VERSION}"
          yq -y ".app.image.tag = \"$IMAGE_TAG\"" values.stage.yaml -i
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add values.stage.yaml
          git commit -m "Update staging image tag to v${VERSION}"
          git push origin main
